sudo: required

cache:
  directories:
    - $HOME/.stack

before_install:
  # Download and unpack the stack executable
  - mkdir -p ${HOME}/.local/bin
  - export PATH=${HOME}/.local/bin:${PATH}
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ${HOME}/.local/bin '*/stack'
  - stack --version
  - stack setup
  # - export PATH=/opt/ghc/7.10.3/bin:$PATH


addons:
  apt:
    sources:
    - hvr-ghc
    packages:
    - ghc-8.0.2

script:
  - cd classic 
  - stack build 
  - stack test